export const serverUrl = "http://localhost:3000";
export const signup = serverUrl + '/auth/signup';
export const login = serverUrl + '/auth/login';
export const get_user_routines = serverUrl + '/routine/user-routines';
export const get_routine_suggestions = serverUrl + '/routine/routines';
export const subscribe_routine = serverUrl + '/routine/register-user-routine';
export const unsubscribe_routine = serverUrl + '/routine/unsubscribe';
export const update_user_details = serverUrl + '/user/edit-user-details';
export const get_user_details = serverUrl + '/user/get-user-details';
